### ISSUE TITLE
Right align numbers in an array without changing the precision

### ISSUE THREAD

**Issue by josdejong** [j-brooke/FracturedJsonJs#10]
Thanks for this excellent library! It really results in much better readable JSON.

I stumbled upon the feature that numbers in a long multiline array are right aligned and the precision of values is adjusted. This can be turned off with the option `DontJustifyNumbers`. I love the right formatting of numbers, that makes sense. However, changing the precision comes with a risk: formatted numbers like `4.0` can be changed into `4`, `1e500` is changed into `Infinity`, and `1e-500` into `0`, because JavaScript numbers can't handle that. This happens for example with the first three numbers in the following array:

```
[
  1e500, 1e-500, 4.0, 
  2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53,
  59, 61, 67, 71, 73, 79, 83, 89, 97, 101, 103, 107, 109, 113
]
```

I would love to have the right formatting of numbers (it looks really neat!), but without the risk of changing the numbers. Is there a way to do that? Or are you open to introduce a new option for that or extend the option `DontJustifyNumbers` to have this "safe" variant?

**Comment by j-brooke** [comment]
Well that `Infinity` conversion is definitely a bug - it produces output that isn't valid JSON.  Thanks for catchig that!

Adding more justification options likely wouldn't difficult as a matter of code, but it presents some settings managment challenges.  Adding new options where the default preserves the old behavior could be done as a minor version change, but actually changing the names of existing settings would require a new major version.

Right now, there's logic to check whether all of the elements of the array qualify for number justification.  If the setting `DontJustifyNumbers` is `true`, of course, then it won't even try.  But if any value in the list, when re-formatted as a 64-bit float, would have more than 15 digits, or would be written in exponential notation, then the list doesn't qualify.  In that case, it treats the values like any other elements: left justified and copied verbatim from the source text.  (I need to add a check for `NaN` to fix the infinity problem.)

The purpose of reformatting the numbers with the same precision is to make the decimal points line up.  Am I right in understanding that you'd like to see an option for right-aligned number lists without reformatting, and without attempting to line up the decimal points?

For example, consider the following list.  (Here I'm using `MaxInlineComplexity=0` and `MaxCompactArrayComplexity=0` to make them show up vertically, but the same logic is used in compact multiline arrays.)

```
[
    1.2              ,
    2345678901234567 ,
    3.456789012345678,
    4.5e67           ,
    5678
]
```

As I understand it, you'd like an option for this:
```
[
                  1.2,
     2345678901234567,
    3.456789012345678,
               4.5e67,
                 5678
]
```

But not this:
```
[
                   1.2              ,
    2345678901234567                ,
                   3.456789012345678,
                   4.5e67           ,
                5678
]
```

Am I right in understanding your suggestion?

**Comment by josdejong** [comment]
You indeed need to be careful with managing new options. I can work out a few proposals if you like. What makes it a bit difficult is that the option name `DontJustifyNumbers` contains a negation `Dont`. Without that, you could put the variants as new values of a singel option, like `JustifyNumbers: true | false | 'alignment' | 'precision' | 'alignmentAndPrecision'` or something like that. 

I hadn't thought about the possibility to align around the decimal point. That is even better than blindly right-aligning the numbers! The core of my request is to have an array of numbers formatted in a human-readable way _without_ altering the numbers themselves (to prevent losing precision of `1e500` and `12345678901234567890`, or intended formatting on a number like `4.00`).

Your third option really looks awesome 😎

**Comment by j-brooke** [comment]
I prefer to keep the settings as similar as possible between the C# and JavaScript versions, so mixing booleans and strings as in your example above isn't practical, but that's easily fixed by making them a C# enum and JavaScript strings.

I wonder if it would make sense to split it into two settings?  Something like `NormalizeNumberListPrecision: true | false` and `NumberListAlignment: left | right | decimal`.  It seems like it would offer lots of flexibility, but I wonder if there are troublesome edge cases that I'm not seeing.

I am concerned, in general, about whether adding extra settings makes the product harder to use for most people.  The more settings there are, the harder it is to find the ones you actually want.  I know I sometimes give up rather than trying to make sense of all the settings in especially complex software like Visual Studio Code.

**Comment by josdejong** [comment]
> I wonder if it would make sense to split it into two settings? Something like `NormalizeNumberListPrecision: true | false` and `NumberListAlignment: left | right | decimal`. It seems like it would offer lots of flexibility, but I wonder if there are troublesome edge cases that I'm not seeing.

That sounds perfect! The option `DontJustifyNumbers` is basically doing two things, best would be to split it into two separate options.

> I am concerned, in general, about whether adding extra settings makes the product harder to use for most people. The more settings there are, the harder it is to find the ones you actually want. I know I sometimes give up rather than trying to make sense of all the settings in especially complex software like Visual Studio Code.

Good to think that trough. For what it is worth: I just started using `FracturedJsonJs`, and found it very straightforward to figure how to configure all of it. That is mostly because each of the options has a very clear name and description, most of them are a simple boolean, and they are all independent of each other. Things become complicated when you have to configure a regular web application these days: configuring Webpack, Babel, TypeScript, ESLint, Jest, CircleCI, Github Actions, Husky etc and make them all work together, involving like ten different config files that are connected with each other. `FracturedJsonJs` is _nowhere_ near any of that 😅.

**Comment by josdejong** [comment]
Off-topic: @j-brooke I just wanted to let you know that I've integrated `FracturedJson` in my [JSON Editor Online](https://jsoneditoronline.org) ([see also article](https://jsoneditoronline.org/indepth/beautify/smart-json-formatting/)), I really love it! I've left attribution in a couple of places (footer, docs, article).

**Comment by j-brooke** [comment]
I created a separate issue for the "infinity" problem.  The formatting improvements suggested in this ticket are definitely worth considering, but the bug fix should happen no matter what.

**Comment by j-brooke** [comment]
I've sketched out how a new set of formatting options might work.  I'd love to hear opinions/suggestions from @josdejong as well as anyone interested with something to say. 

---

Consider this input set:

```
[
    { "val": 123.456 },
    { "val": 234567.8 },
    { "val": 3 },
    { "val": 4.1e-72 },
    { "val": null },
    { "val": 5.67890123 }
]
```

## Current Cases (version 3.1)

Depending on settings, FJ might try to format it like one of these:
```
[
    { "val": 123.456    }, { "val": 234567.8   }, { "val": 3          }, { "val": 4.1e-72    },
    { "val": null       }, { "val": 5.67890123 }
]
```

Or:
```
[
    { "val": 123.456    },
    { "val": 234567.8   },
    { "val": 3          },
    { "val": 4.1e-72    },
    { "val": null       },
    { "val": 5.67890123 }
]
```

If the scientific notation entry is removed and `DontJustifyNumbers=false`:
```
[
    { "val":    123.45600000 },
    { "val": 234567.80000000 },
    { "val":      3.00000000 },
    { "val": null            },
    { "val":      5.67890123 }
]
```

## Proposal Cases

Now, say we get rid of `DontJustifyNumbers`, and instead add two settings, `NumberListAlignment` and `NormalizeNumberListPrecision`.   Here's how that might look:

Case A - When `NumberListAlignment=Left` and `NormalizeNumberListPrecision=false`:
```
[
    { "val": 123.456    },
    { "val": 234567.8   },
    { "val": 3          },
    { "val": 4.1e-72    },
    { "val": null       },
    { "val": 5.67890123 }
]
```

Case B - When `NumberListAlignment=Decimal` and `NormalizeNumberListPrecision=false`:
```
[
    { "val":    123.456      },
    { "val": 234567.8        },
    { "val":      3          },
    { "val":      4.1e-72    },
    { "val":   null          },
    { "val":      5.67890123 }
]
```

Case C - When `NumberListAlignment=Right` and `NormalizeNumberListPrecision=false`:
```
[
    { "val":    123.456 },
    { "val":   234567.8 },
    { "val":          3 },
    { "val":    4.1e-72 },
    { "val":       null },
    { "val": 5.67890123 }
]
```

The `NormalizeNumberListPrecision=true` would be invalidated if we left the `4.1e-72` case in, so we'll remove that for the remaining examples.

Case D - When `NumberListAlignment=Left` and `NormalizeNumberListPrecision=true`:
```
[
    { "val": 123.45600000    },
    { "val": 234567.80000000 },
    { "val": 3.00000000      },
    { "val": null            },
    { "val": 5.67890123      }
]
```

Case E - When `NumberListAlignment=Decimal` and `NormalizeNumberListPrecision=true`:
```
[
    { "val":    123.45600000 },
    { "val": 234567.80000000 },
    { "val":      3.00000000 },
    { "val":   null          },
    { "val":      5.67890123 }
]
```

Case F - When `NumberListAlignment=Right` and `NormalizeNumberListPrecision=true`:
```
[
    { "val":    123.45600000 },
    { "val": 234567.80000000 },
    { "val":      3.00000000 },
    { "val":            null },
    { "val":      5.67890123 }
]
```

## Discussion

Two questions come to mind, looking at these cases:

1. **Is this going too far?**  
    * How many of those cases are actually desirable?  
    * Is there a sensible way to simplify the settings?
    * Is it worth the dev effort improving the FJ code?
    * Is it worth the dev effort for people who upgrade to the new version? (This would require a new major version number.)
2. **Is this going far enough?**
    * What about aligning numbers when the list contains non-number non-null values?
    * What about aligning things other than numbers?

**Comment by josdejong** [comment]
Thanks, this really is a clear overview! Good point to think through if this is not a case of overengineering.

Just to summarize: my main concern is to (a) be able to not alter any numeric formatting and (b) align numeric values in a readable way.

Some thoughts:

1. I doubt whether there is a use case for "Case D", and I think "Case E" and "Case F" are probably both "fine" and equivalent in practice. So, maybe, there is no need for a separate `NormalizeNumberListPrecision: boolean`, and instead it, could be a fourth option of `NumberListAlignment`.
2. Thinking out of the box: would it be a problem to simply remove `NormalizeNumberListPrecision` at all. So: never alter the numeric formatting? Do you know if this option is really used and desired in practice? Given that when the numbers are neatly aligned around the digit using "Case B", the need for it may be gone. Also, having the library never alter the actual data and only altering whitespacing is a strong, safe proposition.
3. Depending on what is easiest to implement, I think it would be totally OK to apply `NumberListAlignment` only when the list contains only numbers and null.
4. I currently cannot think of cases where you would like to alter other things than numbers. So: keep it simple for now, just handling numbers?
5. If you need help implementing this feature, I can see if I can create a PR.

**Comment by j-brooke** [comment]
[Pull request for the C# version here](https://github.com/j-brooke/FracturedJson/pull/29), with examples.

**Comment by j-brooke** [comment]
Version 4.0.0 is now available for the .NET and JavaScript/TypeScript libraries, and the web formatter.  (I'll update the VS Code extension within a few days.)  See the pull request above, but in brief, `DontJustifyNumbers` has been replaced with `NumberListAlignment`.  Three of the options for it - `Left`, `Right`, and `Decimal` line things up using the exact text from the input document for each value.  The fourth - `Normalize` - right-aligns and reformats all of the numbers to the same precision.

**Comment by j-brooke** [comment]
The 4.0.0 version of the VSCode extension is now available too.

**Comment by j-brooke** [comment]
I believe that the 4.0.0 changes satisfy this issue.  Please let me know if you have any further concerns before I close it, @josdejong .

**Comment by josdejong** [comment]
Thats awesome news 😎, I'll test it out tomorrow.

**Comment by josdejong** [comment]
I just tested it out and it works like a charm. I really love it, thanks a lot!
